// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service the frontend calls. Every method that touches a project
 * takes its folder (root) and holds that project's lock, so the background
 * agent and user actions never run at the same time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "../internal/remote/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLocalProject tracks a folder on this computer only (no team).
 */
export function AddLocalProject(folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(3415343716, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddProjectToTeam starts tracking an Ableton project folder as part of a
 * team. It returns quickly; the frontend then commits and uploads the first
 * version with Save, showing its progress.
 */
export function AddProjectToTeam(teamID: string, folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(1141302713, teamID, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Autostart reports whether DAWGit starts when the user signs in to Windows.
 */
export function Autostart(): $CancellablePromise<boolean> {
    return $Call.ByID(4156082814);
}

/**
 * ChooseFolder asks the user for a folder ("" when cancelled).
 */
export function ChooseFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(3880522108, title);
}

/**
 * ConnectTeam adds a team (server address + token, or a connection code) and
 * makes it the current one.
 */
export function ConnectTeam(address: string, token: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(225746720, address, token).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateBranch(root: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3624428965, root, name);
}

/**
 * DeleteProjectFromTeam removes a project from the team's server or storage
 * for everyone. The copy on this computer (if any) is kept, with its history,
 * as a project on this computer only.
 */
export function DeleteProjectFromTeam(teamID: string, projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1271903518, teamID, projectID);
}

/**
 * DownloadProject downloads a team project into parent/<name> Project.
 */
export function DownloadProject(teamID: string, projectID: string, parent: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(3062621418, teamID, projectID, parent).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportVersion writes a version as a separate project folder inside parent
 * and returns its path.
 */
export function ExportVersion(root: string, id: string, parent: string): $CancellablePromise<string> {
    return $Call.ByID(2651241909, root, id, parent);
}

/**
 * ForgetProject removes a project from the list (the folder is untouched).
 */
export function ForgetProject(root: string): $CancellablePromise<void> {
    return $Call.ByID(1105048745, root);
}

/**
 * GoToVersion puts the project folder in the state of a version ("latest"
 * goes back to the newest). discard drops uncommitted changes; force goes
 * ahead while Live is running.
 */
export function GoToVersion(root: string, id: string, discard: boolean, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3139605490, root, id, discard, force).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * KeepThisVersion continues from the older version the project is on: it
 * becomes a new version on top of the latest (shared with the team).
 */
export function KeepThisVersion(root: string, message: string, resolutions: { [_ in string]?: string }): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2867236424, root, message, resolutions).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * LocateProject points a team project at a folder that was moved.
 */
export function LocateProject(teamID: string, projectID: string, folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(4181359348, teamID, projectID, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MergeBranch(root: string, name: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3631821023, root, name, resolutions, force).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenInLive opens a set with its default application (Ableton Live).
 */
export function OpenInLive(root: string, $set: string): $CancellablePromise<void> {
    return $Call.ByID(200971096, root, $set);
}

/**
 * Overview is everything the sidebar and onboarding need.
 */
export function Overview(): $CancellablePromise<$models.Overview | null> {
    return $Call.ByID(20653634).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PreviewMerge(root: string, name: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(1135981589, root, name).then(($result: any) => {
        return $$createType7($result);
    });
}

export function PreviewUpdate(root: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(3558658446, root).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * RemoveTeam disconnects this computer from a team. Project folders stay on
 * disk; they are no longer listed or watched.
 */
export function RemoveTeam(id: string): $CancellablePromise<void> {
    return $Call.ByID(3754118508, id);
}

export function RenameTeam(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(478452658, id, name);
}

/**
 * RenameTeamForEveryone changes the team's own name, on its server or
 * storage; every member's DAWGit follows it.
 */
export function RenameTeamForEveryone(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(280692036, id, name);
}

/**
 * Save records a version and shares it (merging the team's versions first).
 */
export function Save(root: string, message: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1993570256, root, message, resolutions, force).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SelectTeam(id: string): $CancellablePromise<void> {
    return $Call.ByID(2252928460, id);
}

/**
 * ServerProjects lists a team's projects before connecting (onboarding).
 */
export function ServerProjects(address: string, token: string): $CancellablePromise<remote$0.Project[]> {
    return $Call.ByID(898254696, address, token).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetAuthor(name: string): $CancellablePromise<void> {
    return $Call.ByID(2727723748, name);
}

/**
 * SetAutostart turns starting DAWGit at sign-in on or off.
 */
export function SetAutostart(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1324798748, on);
}

/**
 * ShareProject moves a local-only project into a team (see AddProjectToTeam).
 */
export function ShareProject(root: string, teamID: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(1658918021, root, teamID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ShowFolder(root: string): $CancellablePromise<void> {
    return $Call.ByID(2097789072, root);
}

/**
 * Signature changes when a set in the project is saved (or the project moves
 * to another version). It only looks at file sizes and times, and takes no
 * lock, so the frontend polls it to notice Ctrl+S in Live right away.
 */
export function Signature(root: string): $CancellablePromise<string> {
    return $Call.ByID(1626727493, root);
}

export function State(root: string): $CancellablePromise<$models.State | null> {
    return $Call.ByID(1946832782, root).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SwitchBranch(root: string, name: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(4167079521, root, name, force).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Update brings in the team's latest versions.
 */
export function Update(root: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(4141298428, root, resolutions, force).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Version is the DAWGit release number.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2431199839);
}

// Private type creation functions
const $$createType0 = $models.TeamProject.createFrom;
const $$createType1 = $models.TeamSummary.createFrom;
const $$createType2 = $models.Result.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Overview.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.Preview.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = remote$0.Project.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.State.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
