// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service the frontend calls. Every method that touches a project
 * takes its folder (root) and holds that project's lock, so the background
 * agent and user actions never run at the same time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "../internal/remote/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLocalProject tracks a folder on this computer only (no team).
 */
export function AddLocalProject(folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(3415343716, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddProjectToTeam starts tracking an Ableton project folder as part of a
 * team. It returns quickly; the frontend then commits and uploads the first
 * version with Save, showing its progress.
 */
export function AddProjectToTeam(teamID: string, folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(1141302713, teamID, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Autostart reports whether DAWGit starts when the user signs in to Windows.
 */
export function Autostart(): $CancellablePromise<boolean> {
    return $Call.ByID(4156082814);
}

/**
 * CheckUpdate asks GitHub for a newer release (at most every 6 hours) and
 * returns it, or nil when this is the newest. DAWGIT_NO_UPDATE_CHECK=1 turns
 * it off; DAWGIT_DEV_VERSION pretends to be another version (testing).
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(586574094).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ChooseFolder asks the user for a folder ("" when cancelled).
 */
export function ChooseFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(3880522108, title);
}

/**
 * ConnectTeam adds a team (server address + token, or a connection code) and
 * makes it the current one.
 */
export function ConnectTeam(address: string, token: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(225746720, address, token).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CreateBranch(root: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3624428965, root, name);
}

/**
 * DeleteProjectFromTeam removes a project from the team's server or storage
 * for everyone. The copy on this computer (if any) is kept, with its history,
 * as a project on this computer only.
 */
export function DeleteProjectFromTeam(teamID: string, projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1271903518, teamID, projectID);
}

/**
 * DiscardAndUpdate drops uncommitted changes and takes the team's latest
 * versions of this branch.
 */
export function DiscardAndUpdate(root: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2611281035, root, resolutions, force).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DiscardFile puts one file back as it is in the version the project is on.
 */
export function DiscardFile(root: string, file: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2822748111, root, file, force).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DownloadProject downloads a team project into parent/<name> Project.
 */
export function DownloadProject(teamID: string, projectID: string, parent: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(3062621418, teamID, projectID, parent).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportVersion writes a version as a separate project folder inside parent
 * and returns its path.
 */
export function ExportVersion(root: string, id: string, parent: string): $CancellablePromise<string> {
    return $Call.ByID(2651241909, root, id, parent);
}

/**
 * FileDiff describes how a set changed between two versions ("" for from:
 * the set was added), as diff lines.
 */
export function FileDiff(root: string, file: string, $from: string, to: string): $CancellablePromise<string[]> {
    return $Call.ByID(2746812856, root, file, $from, to).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * FileHistory lists the versions of the current branch that changed path.
 */
export function FileHistory(root: string, file: string): $CancellablePromise<$models.FileVersion[]> {
    return $Call.ByID(2582398293, root, file).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ForgetProject removes a project from the list (the folder is untouched).
 */
export function ForgetProject(root: string): $CancellablePromise<void> {
    return $Call.ByID(1105048745, root);
}

/**
 * GoToVersion puts the project folder in the state of a version ("latest"
 * goes back to the newest). discard drops uncommitted changes; force goes
 * ahead while Live is running.
 */
export function GoToVersion(root: string, id: string, discard: boolean, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3139605490, root, id, discard, force).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * KeepThisVersion continues from the older version the project is on: it
 * becomes a new version on top of the latest (shared with the team).
 */
export function KeepThisVersion(root: string, message: string, resolutions: { [_ in string]?: string }): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2867236424, root, message, resolutions).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LocateProject points a team project at a folder that was moved.
 */
export function LocateProject(teamID: string, projectID: string, folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(4181359348, teamID, projectID, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MergeBranch(root: string, name: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3631821023, root, name, resolutions, force).then(($result: any) => {
        return $$createType5($result);
    });
}

export function MergeVersion(root: string, id: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3024291569, root, id, resolutions, force).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenInLive opens a set with its default application (Ableton Live).
 */
export function OpenInLive(root: string, $set: string): $CancellablePromise<void> {
    return $Call.ByID(200971096, root, $set);
}

/**
 * OpenURL opens a DAWGit page (release notes, installer download) in the
 * browser. Other addresses are refused.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3584934946, url);
}

/**
 * Overview is everything the sidebar and onboarding need.
 */
export function Overview(): $CancellablePromise<$models.Overview | null> {
    return $Call.ByID(20653634).then(($result: any) => {
        return $$createType10($result);
    });
}

export function PreviewMerge(root: string, name: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(1135981589, root, name).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * PreviewMergeVersion previews merging any version (e.g. one in the middle
 * of another branch) into the current branch.
 */
export function PreviewMergeVersion(root: string, id: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(730100359, root, id).then(($result: any) => {
        return $$createType12($result);
    });
}

export function PreviewUpdate(root: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(3558658446, root).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ProjectFiles lists the changed files; with all, every file in the project
 * folder (files DAWGit leaves out are "ignored").
 */
export function ProjectFiles(root: string, all: boolean): $CancellablePromise<$models.ProjectFile[]> {
    return $Call.ByID(445585849, root, all).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * RemoveTeam disconnects this computer from a team. Project folders stay on
 * disk; they are no longer listed or watched.
 */
export function RemoveTeam(id: string): $CancellablePromise<void> {
    return $Call.ByID(3754118508, id);
}

export function RenameTeam(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(478452658, id, name);
}

/**
 * RenameTeamForEveryone changes the team's own name, on its server or
 * storage; every member's DAWGit follows it.
 */
export function RenameTeamForEveryone(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(280692036, id, name);
}

/**
 * Save records a version and shares it (merging the team's versions first).
 * 
 * combine: when teammates committed on this branch in the meantime, their
 * versions are combined with this one. Without it such a save changes
 * nothing and returns action "behind", so the user decides (combine, new
 * branch, or discard) with a preview.
 */
export function Save(root: string, message: string, combine: boolean, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1993570256, root, message, combine, resolutions, force).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SelectTeam(id: string): $CancellablePromise<void> {
    return $Call.ByID(2252928460, id);
}

/**
 * ServerProjects lists a team's projects before connecting (onboarding).
 */
export function ServerProjects(address: string, token: string): $CancellablePromise<remote$0.Project[]> {
    return $Call.ByID(898254696, address, token).then(($result: any) => {
        return $$createType16($result);
    });
}

export function SetAuthor(name: string): $CancellablePromise<void> {
    return $Call.ByID(2727723748, name);
}

/**
 * SetAutostart turns starting DAWGit at sign-in on or off.
 */
export function SetAutostart(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1324798748, on);
}

/**
 * SetIdentity sets who this computer is in a team: an existing member
 * (memberID, e.g. the same person on another computer) or a new one
 * (memberID ""). The name goes to the team's member list, so everyone sees
 * it on all of that member's versions, old ones included.
 */
export function SetIdentity(teamID: string, memberID: string, name: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(1822841893, teamID, memberID, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ShareProject moves a local-only project into a team (see AddProjectToTeam).
 */
export function ShareProject(root: string, teamID: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(1658918021, root, teamID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ShowFile opens Explorer with the file selected.
 */
export function ShowFile(root: string, file: string): $CancellablePromise<void> {
    return $Call.ByID(3695986834, root, file);
}

export function ShowFolder(root: string): $CancellablePromise<void> {
    return $Call.ByID(2097789072, root);
}

/**
 * Signature changes when a set in the project is saved (or the project moves
 * to another version). It only looks at file sizes and times, and takes no
 * lock, so the frontend polls it to notice Ctrl+S in Live right away.
 */
export function Signature(root: string): $CancellablePromise<string> {
    return $Call.ByID(1626727493, root);
}

export function State(root: string): $CancellablePromise<$models.State | null> {
    return $Call.ByID(1946832782, root).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SwitchBranch(root: string, name: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(4167079521, root, name, force).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * TeamMembers lists a team's members (to pick yourself on a new computer).
 */
export function TeamMembers(teamID: string): $CancellablePromise<remote$0.Member[]> {
    return $Call.ByID(2113787423, teamID).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * Update brings in the team's latest versions.
 */
export function Update(root: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(4141298428, root, resolutions, force).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Version is the DAWGit release number.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2431199839);
}

// Private type creation functions
const $$createType0 = $models.TeamProject.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.TeamSummary.createFrom;
const $$createType4 = $models.Result.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $models.FileVersion.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.Overview.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.Preview.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.ProjectFile.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = remote$0.Project.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.State.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = remote$0.Member.createFrom;
const $$createType20 = $Create.Array($$createType19);
