// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service the frontend calls. Every method that touches a project
 * takes its folder (root) and holds that project's lock, so the background
 * agent and user actions never run at the same time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "../internal/remote/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddProject starts tracking an Ableton project folder (or opens one that is
 * already tracked).
 */
export function AddProject(root: string, author: string): $CancellablePromise<$models.ProjectSummary> {
    return $Call.ByID(1121292353, root, author).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Autostart reports whether DAWGit starts when the user signs in to Windows.
 */
export function Autostart(): $CancellablePromise<boolean> {
    return $Call.ByID(4156082814);
}

/**
 * ChooseFolder asks the user for a folder ("" when cancelled).
 */
export function ChooseFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(3880522108, title);
}

/**
 * Connect links a project to a team server and shares it.
 */
export function Connect(root: string, url: string, token: string): $CancellablePromise<void> {
    return $Call.ByID(164877153, root, url, token);
}

export function CreateBranch(root: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3624428965, root, name);
}

/**
 * JoinProject downloads a project from the server into parent/<name> Project.
 */
export function JoinProject(url: string, token: string, projectID: string, parent: string, author: string): $CancellablePromise<$models.ProjectSummary> {
    return $Call.ByID(3117186410, url, token, projectID, parent, author).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MergeBranch(root: string, name: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3631821023, root, name, resolutions, force).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenInLive opens a set with its default application (Ableton Live).
 */
export function OpenInLive(root: string, $set: string): $CancellablePromise<void> {
    return $Call.ByID(200971096, root, $set);
}

export function PreviewMerge(root: string, name: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(1135981589, root, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function PreviewUpdate(root: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(3558658446, root).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Projects(): $CancellablePromise<$models.ProjectSummary[]> {
    return $Call.ByID(2386848479).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RemoveProject(root: string): $CancellablePromise<void> {
    return $Call.ByID(66093214, root);
}

/**
 * Save records a version and shares it (merging the team's versions first).
 */
export function Save(root: string, message: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1993570256, root, message, resolutions, force).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ServerProjects lists the projects on a server (for joining one).
 */
export function ServerProjects(url: string, token: string): $CancellablePromise<remote$0.Project[]> {
    return $Call.ByID(898254696, url, token).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SetAutostart turns starting DAWGit at sign-in on or off.
 */
export function SetAutostart(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1324798748, on);
}

export function ShowFolder(root: string): $CancellablePromise<void> {
    return $Call.ByID(2097789072, root);
}

export function State(root: string): $CancellablePromise<$models.State | null> {
    return $Call.ByID(1946832782, root).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SwitchBranch(root: string, name: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(4167079521, root, name, force).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Update brings in the team's latest versions.
 */
export function Update(root: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(4141298428, root, resolutions, force).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProjectSummary.createFrom;
const $$createType1 = $models.Result.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.Preview.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = remote$0.Project.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.State.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
