// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../internal/project/models.js";

export class Branch {
    "name": string;
    "current": boolean;
    "latest": Version | null;

    /** Creates a new Branch instance. */
    constructor($$source: Partial<Branch> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }
        if (!("latest" in $$source)) {
            this["latest"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     */
    static createFrom($$source: any = {}): Branch {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField2_0($$parsedSource["latest"]);
        }
        return new Branch($$parsedSource as Partial<Branch>);
    }
}

export class Change {
    "path": string;

    /**
     * added | modified | deleted
     */
    "status": string;

    /**
     * semantic diff lines for sets
     */
    "details": string[];

    /** Creates a new Change instance. */
    constructor($$source: Partial<Change> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Change instance from a string or object.
     */
    static createFrom($$source: any = {}): Change {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        return new Change($$parsedSource as Partial<Change>);
    }
}

export class Conflict {
    "key": string;
    "file": string;
    "unit": string;
    "description": string;
    "canKeepBoth": boolean;

    /** Creates a new Conflict instance. */
    constructor($$source: Partial<Conflict> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("canKeepBoth" in $$source)) {
            this["canKeepBoth"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conflict instance from a string or object.
     */
    static createFrom($$source: any = {}): Conflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conflict($$parsedSource as Partial<Conflict>);
    }
}

export class Overview {
    "author": string;
    "teams": TeamSummary[];
    "currentTeam": string;

    /**
     * of the current team
     */
    "projects": TeamProject[];
    "teamError": string;

    /**
     * kept on this computer only
     */
    "local": TeamProject[];

    /** Creates a new Overview instance. */
    constructor($$source: Partial<Overview> = {}) {
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("teams" in $$source)) {
            this["teams"] = [];
        }
        if (!("currentTeam" in $$source)) {
            this["currentTeam"] = "";
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }
        if (!("teamError" in $$source)) {
            this["teamError"] = "";
        }
        if (!("local" in $$source)) {
            this["local"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     */
    static createFrom($$source: any = {}): Overview {
        const $$createField1_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("teams" in $$parsedSource) {
            $$parsedSource["teams"] = $$createField1_0($$parsedSource["teams"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField3_0($$parsedSource["projects"]);
        }
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField5_0($$parsedSource["local"]);
        }
        return new Overview($$parsedSource as Partial<Overview>);
    }
}

export class Preview {
    /**
     * up-to-date | ahead | fast-forward | merge
     */
    "action": string;
    "versions": Version[];
    "changes": Change[];
    "conflicts": Conflict[];

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField1_0($$parsedSource["versions"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField2_0($$parsedSource["changes"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField3_0($$parsedSource["conflicts"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

/**
 * Result of save / update / merge / switch.
 */
export class Result {
    "action": string;
    "log": string[];
    "relinked": string[];

    /**
     * Conflicts need decisions; nothing was changed. Call again with
     * resolutions keyed by Conflict.Key.
     */
    "conflicts": Conflict[];

    /**
     * LiveRunning: a set of this project is open in Ableton Live and must be
     * closed first (OpenSet names it; "" when it cannot be told); call again
     * with force when it is closed.
     */
    "liveRunning": boolean;
    "openSet": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("log" in $$source)) {
            this["log"] = [];
        }
        if (!("relinked" in $$source)) {
            this["relinked"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("liveRunning" in $$source)) {
            this["liveRunning"] = false;
        }
        if (!("openSet" in $$source)) {
            this["openSet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField1_0($$parsedSource["log"]);
        }
        if ("relinked" in $$parsedSource) {
            $$parsedSource["relinked"] = $$createField2_0($$parsedSource["relinked"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField3_0($$parsedSource["conflicts"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

export class State {
    "root": string;
    "name": string;
    "author": string;
    "branch": string;
    "remoteUrl": string;

    /**
     * "" for a project kept on this computer only
     */
    "teamId": string;
    "teamName": string;
    "online": boolean;

    /**
     * why the server is unreachable
     */
    "offline": string;

    /**
     * a set of this project is open in Live
     */
    "liveRunning": boolean;
    "head": string;

    /**
     * .als files in the project folder
     */
    "sets": string[];

    /**
     * OlderVersion is the version the project was moved back to (Go to
     * version); nil on the latest version. Latest is the branch's newest.
     */
    "olderVersion": Version | null;
    "latest": string;
    "changes": Change[];
    "myEdits": project$0.TrackEdit[];
    "incoming": Version[];
    "teammates": Teammate[];
    "overlaps": string[];
    "history": Version[];
    "branches": Branch[];

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("remoteUrl" in $$source)) {
            this["remoteUrl"] = "";
        }
        if (!("teamId" in $$source)) {
            this["teamId"] = "";
        }
        if (!("teamName" in $$source)) {
            this["teamName"] = "";
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("offline" in $$source)) {
            this["offline"] = "";
        }
        if (!("liveRunning" in $$source)) {
            this["liveRunning"] = false;
        }
        if (!("head" in $$source)) {
            this["head"] = "";
        }
        if (!("sets" in $$source)) {
            this["sets"] = [];
        }
        if (!("olderVersion" in $$source)) {
            this["olderVersion"] = null;
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("myEdits" in $$source)) {
            this["myEdits"] = [];
        }
        if (!("incoming" in $$source)) {
            this["incoming"] = [];
        }
        if (!("teammates" in $$source)) {
            this["teammates"] = [];
        }
        if (!("overlaps" in $$source)) {
            this["overlaps"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType1;
        const $$createField14_0 = $$createType9;
        const $$createField15_0 = $$createType13;
        const $$createField16_0 = $$createType7;
        const $$createField17_0 = $$createType15;
        const $$createField18_0 = $$createType2;
        const $$createField19_0 = $$createType7;
        const $$createField20_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sets" in $$parsedSource) {
            $$parsedSource["sets"] = $$createField11_0($$parsedSource["sets"]);
        }
        if ("olderVersion" in $$parsedSource) {
            $$parsedSource["olderVersion"] = $$createField12_0($$parsedSource["olderVersion"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField14_0($$parsedSource["changes"]);
        }
        if ("myEdits" in $$parsedSource) {
            $$parsedSource["myEdits"] = $$createField15_0($$parsedSource["myEdits"]);
        }
        if ("incoming" in $$parsedSource) {
            $$parsedSource["incoming"] = $$createField16_0($$parsedSource["incoming"]);
        }
        if ("teammates" in $$parsedSource) {
            $$parsedSource["teammates"] = $$createField17_0($$parsedSource["teammates"]);
        }
        if ("overlaps" in $$parsedSource) {
            $$parsedSource["overlaps"] = $$createField18_0($$parsedSource["overlaps"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField19_0($$parsedSource["history"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField20_0($$parsedSource["branches"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * TeamProject is a project as the sidebar shows it.
 */
export class TeamProject {
    "id": string;
    "name": string;
    "root": string;

    /**
     * Status: "downloaded" (folder here), "remote" (on the team only),
     * "missing" (downloaded before, folder not found), "local" (no team).
     */
    "status": string;
    "branch": string;

    /** Creates a new TeamProject instance. */
    constructor($$source: Partial<TeamProject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamProject instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamProject($$parsedSource as Partial<TeamProject>);
    }
}

export class TeamSummary {
    "id": string;
    "name": string;
    "address": string;
    "isStorage": boolean;

    /** Creates a new TeamSummary instance. */
    constructor($$source: Partial<TeamSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("isStorage" in $$source)) {
            this["isStorage"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamSummary($$parsedSource as Partial<TeamSummary>);
    }
}

export class Teammate {
    "author": string;
    "updated": string;
    "edits": project$0.TrackEdit[];

    /** Creates a new Teammate instance. */
    constructor($$source: Partial<Teammate> = {}) {
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("updated" in $$source)) {
            this["updated"] = "";
        }
        if (!("edits" in $$source)) {
            this["edits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Teammate instance from a string or object.
     */
    static createFrom($$source: any = {}): Teammate {
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edits" in $$parsedSource) {
            $$parsedSource["edits"] = $$createField2_0($$parsedSource["edits"]);
        }
        return new Teammate($$parsedSource as Partial<Teammate>);
    }
}

export class Version {
    "id": string;
    "short": string;
    "author": string;

    /**
     * RFC 3339
     */
    "time": string;
    "message": string;
    "parents": string[];

    /**
     * server branches whose latest version this is
     */
    "branches": string[];

    /**
     * InBranch: the current branch already contains this version (only set
     * in State.History); other versions can be merged in.
     */
    "inBranch": boolean;

    /** Creates a new Version instance. */
    constructor($$source: Partial<Version> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("short" in $$source)) {
            this["short"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("parents" in $$source)) {
            this["parents"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }
        if (!("inBranch" in $$source)) {
            this["inBranch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     */
    static createFrom($$source: any = {}): Version {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField5_0($$parsedSource["parents"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField6_0($$parsedSource["branches"]);
        }
        return new Version($$parsedSource as Partial<Version>);
    }
}

// Private type creation functions
const $$createType0 = Version.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = TeamSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = TeamProject.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = Change.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Conflict.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = project$0.TrackEdit.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = Teammate.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = Branch.createFrom;
const $$createType17 = $Create.Array($$createType16);
