// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../internal/project/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "../internal/remote/models.js";

export class Branch {
    "name": string;
    "current": boolean;
    "latest": Version | null;

    /** Creates a new Branch instance. */
    constructor($$source: Partial<Branch> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }
        if (!("latest" in $$source)) {
            this["latest"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     */
    static createFrom($$source: any = {}): Branch {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField2_0($$parsedSource["latest"]);
        }
        return new Branch($$parsedSource as Partial<Branch>);
    }
}

export class Change {
    "path": string;

    /**
     * added | modified | deleted
     */
    "status": string;

    /**
     * semantic diff lines for sets
     */
    "details": string[];

    /** Creates a new Change instance. */
    constructor($$source: Partial<Change> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Change instance from a string or object.
     */
    static createFrom($$source: any = {}): Change {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        return new Change($$parsedSource as Partial<Change>);
    }
}

export class Conflict {
    "key": string;
    "file": string;
    "unit": string;
    "description": string;
    "canKeepBoth": boolean;

    /** Creates a new Conflict instance. */
    constructor($$source: Partial<Conflict> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("canKeepBoth" in $$source)) {
            this["canKeepBoth"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conflict instance from a string or object.
     */
    static createFrom($$source: any = {}): Conflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conflict($$parsedSource as Partial<Conflict>);
    }
}

/**
 * ConvertFormat is a format the Convert dialog offers.
 */
export class ConvertFormat {
    "id": string;
    "name": string;
    "ext": string;

    /**
     * kbps, first is the default; none for lossless
     */
    "bitrates": number[];

    /**
     * sample rates it takes (Hz)
     */
    "rates": number[];

    /**
     * bit depths to choose from (FLAC)
     */
    "bits": number[];

    /** Creates a new ConvertFormat instance. */
    constructor($$source: Partial<ConvertFormat> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ext" in $$source)) {
            this["ext"] = "";
        }
        if (!("bitrates" in $$source)) {
            this["bitrates"] = [];
        }
        if (!("rates" in $$source)) {
            this["rates"] = [];
        }
        if (!("bits" in $$source)) {
            this["bits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvertFormat instance from a string or object.
     */
    static createFrom($$source: any = {}): ConvertFormat {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bitrates" in $$parsedSource) {
            $$parsedSource["bitrates"] = $$createField3_0($$parsedSource["bitrates"]);
        }
        if ("rates" in $$parsedSource) {
            $$parsedSource["rates"] = $$createField4_0($$parsedSource["rates"]);
        }
        if ("bits" in $$parsedSource) {
            $$parsedSource["bits"] = $$createField5_0($$parsedSource["bits"]);
        }
        return new ConvertFormat($$parsedSource as Partial<ConvertFormat>);
    }
}

/**
 * FileVersion is a version that changed a file.
 */
export class FileVersion {
    "version": Version;

    /**
     * added | modified | deleted
     */
    "status": string;

    /** Creates a new FileVersion instance. */
    constructor($$source: Partial<FileVersion> = {}) {
        if (!("version" in $$source)) {
            this["version"] = (new Version());
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): FileVersion {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField0_0($$parsedSource["version"]);
        }
        return new FileVersion($$parsedSource as Partial<FileVersion>);
    }
}

/**
 * FoundProject is a project on this computer that belongs to a team.
 */
export class FoundProject {
    "root": string;
    "name": string;

    /** Creates a new FoundProject instance. */
    constructor($$source: Partial<FoundProject> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FoundProject instance from a string or object.
     */
    static createFrom($$source: any = {}): FoundProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FoundProject($$parsedSource as Partial<FoundProject>);
    }
}

export class Overview {
    "author": string;
    "teams": TeamSummary[];
    "currentTeam": string;

    /**
     * of the current team
     */
    "projects": TeamProject[];
    "teamError": string;

    /**
     * kept on this computer only
     */
    "local": TeamProject[];

    /** Creates a new Overview instance. */
    constructor($$source: Partial<Overview> = {}) {
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("teams" in $$source)) {
            this["teams"] = [];
        }
        if (!("currentTeam" in $$source)) {
            this["currentTeam"] = "";
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }
        if (!("teamError" in $$source)) {
            this["teamError"] = "";
        }
        if (!("local" in $$source)) {
            this["local"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     */
    static createFrom($$source: any = {}): Overview {
        const $$createField1_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("teams" in $$parsedSource) {
            $$parsedSource["teams"] = $$createField1_0($$parsedSource["teams"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField3_0($$parsedSource["projects"]);
        }
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField5_0($$parsedSource["local"]);
        }
        return new Overview($$parsedSource as Partial<Overview>);
    }
}

export class Preview {
    /**
     * up-to-date | ahead | fast-forward | merge
     */
    "action": string;
    "versions": Version[];
    "changes": Change[];
    "conflicts": Conflict[];

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField1_0($$parsedSource["versions"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField2_0($$parsedSource["changes"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField3_0($$parsedSource["conflicts"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

/**
 * ProjectFile is a file as the Changes tab lists it.
 */
export class ProjectFile {
    "path": string;

    /**
     * added | modified | deleted | unchanged | ignored
     */
    "status": string;
    "size": number;

    /**
     * set | live (clip, preset, rack) | audio | midi | other
     */
    "kind": string;

    /**
     * Live is the Live that last saved a set, e.g. "Ableton Live 12.3.1".
     */
    "live": string;

    /** Creates a new ProjectFile instance. */
    constructor($$source: Partial<ProjectFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("live" in $$source)) {
            this["live"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectFile($$parsedSource as Partial<ProjectFile>);
    }
}

/**
 * Result of save / update / merge / switch.
 */
export class Result {
    "action": string;
    "log": string[];
    "relinked": string[];

    /**
     * Conflicts need decisions; nothing was changed. Call again with
     * resolutions keyed by Conflict.Key.
     */
    "conflicts": Conflict[];

    /**
     * LiveRunning: a set of this project is open in Ableton Live and must be
     * closed first (OpenSet names it; "" when it cannot be told); call again
     * with force when it is closed.
     */
    "liveRunning": boolean;
    "openSet": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("log" in $$source)) {
            this["log"] = [];
        }
        if (!("relinked" in $$source)) {
            this["relinked"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("liveRunning" in $$source)) {
            this["liveRunning"] = false;
        }
        if (!("openSet" in $$source)) {
            this["openSet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField1_0($$parsedSource["log"]);
        }
        if ("relinked" in $$parsedSource) {
            $$parsedSource["relinked"] = $$createField2_0($$parsedSource["relinked"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField3_0($$parsedSource["conflicts"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

export class State {
    "root": string;
    "name": string;
    "author": string;
    "branch": string;
    "remoteUrl": string;

    /**
     * "" for a project kept on this computer only
     */
    "teamId": string;
    "teamName": string;

    /**
     * TeamChecked: the team fields below come from a TeamState call (false
     * until one ran for this project since DAWGit started).
     */
    "teamChecked": boolean;
    "online": boolean;

    /**
     * why the server is unreachable
     */
    "offline": string;

    /**
     * a set of this project is open in Live
     */
    "liveRunning": boolean;
    "head": string;

    /**
     * .als files in the project folder
     */
    "sets": string[];

    /**
     * OlderVersion is the version the project was moved back to (Go to
     * version); nil on the latest version. Latest is the branch's newest.
     */
    "olderVersion": Version | null;
    "latest": string;
    "changes": Change[];
    "myEdits": project$0.TrackEdit[];
    "incoming": Version[];
    "history": Version[];
    "branches": Branch[];

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("remoteUrl" in $$source)) {
            this["remoteUrl"] = "";
        }
        if (!("teamId" in $$source)) {
            this["teamId"] = "";
        }
        if (!("teamName" in $$source)) {
            this["teamName"] = "";
        }
        if (!("teamChecked" in $$source)) {
            this["teamChecked"] = false;
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("offline" in $$source)) {
            this["offline"] = "";
        }
        if (!("liveRunning" in $$source)) {
            this["liveRunning"] = false;
        }
        if (!("head" in $$source)) {
            this["head"] = "";
        }
        if (!("sets" in $$source)) {
            this["sets"] = [];
        }
        if (!("olderVersion" in $$source)) {
            this["olderVersion"] = null;
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("myEdits" in $$source)) {
            this["myEdits"] = [];
        }
        if (!("incoming" in $$source)) {
            this["incoming"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType1;
        const $$createField15_0 = $$createType10;
        const $$createField16_0 = $$createType14;
        const $$createField17_0 = $$createType8;
        const $$createField18_0 = $$createType8;
        const $$createField19_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sets" in $$parsedSource) {
            $$parsedSource["sets"] = $$createField12_0($$parsedSource["sets"]);
        }
        if ("olderVersion" in $$parsedSource) {
            $$parsedSource["olderVersion"] = $$createField13_0($$parsedSource["olderVersion"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField15_0($$parsedSource["changes"]);
        }
        if ("myEdits" in $$parsedSource) {
            $$parsedSource["myEdits"] = $$createField16_0($$parsedSource["myEdits"]);
        }
        if ("incoming" in $$parsedSource) {
            $$parsedSource["incoming"] = $$createField17_0($$parsedSource["incoming"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField18_0($$parsedSource["history"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField19_0($$parsedSource["branches"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * TeamConnection is how this computer reaches a team: storage fields, or a
 * server address and token.
 */
export class TeamConnection {
    "storage": boolean;
    "settings": remote$0.Storage;
    "address": string;
    "token": string;

    /** Creates a new TeamConnection instance. */
    constructor($$source: Partial<TeamConnection> = {}) {
        if (!("storage" in $$source)) {
            this["storage"] = false;
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new remote$0.Storage());
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamConnection {
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField1_0($$parsedSource["settings"]);
        }
        return new TeamConnection($$parsedSource as Partial<TeamConnection>);
    }
}

/**
 * TeamPart is the team's side of a project's state (see TeamState).
 */
export class TeamPart {
    "online": boolean;
    "offline": string;
    "branches": Branch[];
    "incoming": Version[];

    /**
     * all branches, with the team's
     */
    "history": Version[];
    "olderVersion": Version | null;

    /** Creates a new TeamPart instance. */
    constructor($$source: Partial<TeamPart> = {}) {
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("offline" in $$source)) {
            this["offline"] = "";
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }
        if (!("incoming" in $$source)) {
            this["incoming"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("olderVersion" in $$source)) {
            this["olderVersion"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamPart instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamPart {
        const $$createField2_0 = $$createType16;
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField2_0($$parsedSource["branches"]);
        }
        if ("incoming" in $$parsedSource) {
            $$parsedSource["incoming"] = $$createField3_0($$parsedSource["incoming"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField4_0($$parsedSource["history"]);
        }
        if ("olderVersion" in $$parsedSource) {
            $$parsedSource["olderVersion"] = $$createField5_0($$parsedSource["olderVersion"]);
        }
        return new TeamPart($$parsedSource as Partial<TeamPart>);
    }
}

/**
 * TeamProject is a project as the sidebar shows it.
 */
export class TeamProject {
    "id": string;
    "name": string;
    "root": string;

    /**
     * Status: "downloaded" (folder here), "remote" (on the team only),
     * "missing" (downloaded before, folder not found), "local" (no team).
     */
    "status": string;
    "branch": string;

    /** Creates a new TeamProject instance. */
    constructor($$source: Partial<TeamProject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamProject instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamProject($$parsedSource as Partial<TeamProject>);
    }
}

export class TeamSummary {
    "id": string;
    "name": string;
    "address": string;
    "isStorage": boolean;

    /**
     * Who this computer is in the team ("" until chosen).
     */
    "memberId": string;
    "memberName": string;

    /** Creates a new TeamSummary instance. */
    constructor($$source: Partial<TeamSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("isStorage" in $$source)) {
            this["isStorage"] = false;
        }
        if (!("memberId" in $$source)) {
            this["memberId"] = "";
        }
        if (!("memberName" in $$source)) {
            this["memberName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamSummary($$parsedSource as Partial<TeamSummary>);
    }
}

/**
 * UpdateInfo describes a newer release than the one running.
 */
export class UpdateInfo {
    "version": string;

    /**
     * what's new
     */
    "pageUrl": string;

    /**
     * the installer ("" if none)
     */
    "downloadUrl": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("pageUrl" in $$source)) {
            this["pageUrl"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            this["downloadUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

export class Version {
    "id": string;
    "short": string;
    "author": string;

    /**
     * RFC 3339
     */
    "time": string;
    "message": string;
    "parents": string[];

    /**
     * server branches whose latest version this is
     */
    "branches": string[];

    /**
     * team member id ("" for older versions)
     */
    "authorId": string;

    /**
     * InBranch: the current branch already contains this version (only set
     * in State.History); other versions can be merged in.
     */
    "inBranch": boolean;

    /** Creates a new Version instance. */
    constructor($$source: Partial<Version> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("short" in $$source)) {
            this["short"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("parents" in $$source)) {
            this["parents"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }
        if (!("authorId" in $$source)) {
            this["authorId"] = "";
        }
        if (!("inBranch" in $$source)) {
            this["inBranch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     */
    static createFrom($$source: any = {}): Version {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField5_0($$parsedSource["parents"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField6_0($$parsedSource["branches"]);
        }
        return new Version($$parsedSource as Partial<Version>);
    }
}

// Private type creation functions
const $$createType0 = Version.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = TeamSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = TeamProject.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = Change.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Conflict.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = project$0.TrackEdit.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Branch.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = remote$0.Storage.createFrom;
