// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Applied is a preset in use for a folder ("" is the project folder).
 */
export class Applied {
    "folder": string;
    "preset": string;

    /**
     * no .dawgit.yaml: found from the folder
     */
    "detected": boolean;

    /** Creates a new Applied instance. */
    constructor($$source: Partial<Applied> = {}) {
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("detected" in $$source)) {
            this["detected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Applied instance from a string or object.
     */
    static createFrom($$source: any = {}): Applied {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Applied($$parsedSource as Partial<Applied>);
    }
}
