// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClipSummary {
    "name": string;
    "color": number;

    /**
     * beats (arrangement)
     */
    "start": number;
    "end": number;

    /**
     * session: the scene's index; -1 in the arrangement
     */
    "slot": number;

    /**
     * deactivated clip
     */
    "disabled": boolean;

    /** Creates a new ClipSummary instance. */
    constructor($$source: Partial<ClipSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = 0;
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("slot" in $$source)) {
            this["slot"] = 0;
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipSummary($$parsedSource as Partial<ClipSummary>);
    }
}

export class Locator {
    "name": string;

    /**
     * beats
     */
    "time": number;

    /** Creates a new Locator instance. */
    constructor($$source: Partial<Locator> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Locator instance from a string or object.
     */
    static createFrom($$source: any = {}): Locator {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Locator($$parsedSource as Partial<Locator>);
    }
}

/**
 * Overview is what a set looks like at a glance: its tracks as Live shows
 * them in Arrangement and Session view, without the devices' insides.
 */
export class Overview {
    "creator": string;
    "tempo": number;

    /**
     * numerator, denominator
     */
    "timeSig": number[];

    /**
     * beats: the end of the last arrangement clip
     */
    "length": number;
    "scenes": string[];
    "locators": Locator[];
    "tracks": TrackSummary[];
    "main": TrackSummary;

    /** Creates a new Overview instance. */
    constructor($$source: Partial<Overview> = {}) {
        if (!("creator" in $$source)) {
            this["creator"] = "";
        }
        if (!("tempo" in $$source)) {
            this["tempo"] = 0;
        }
        if (!("timeSig" in $$source)) {
            this["timeSig"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }
        if (!("scenes" in $$source)) {
            this["scenes"] = [];
        }
        if (!("locators" in $$source)) {
            this["locators"] = [];
        }
        if (!("tracks" in $$source)) {
            this["tracks"] = [];
        }
        if (!("main" in $$source)) {
            this["main"] = (new TrackSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     */
    static createFrom($$source: any = {}): Overview {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scenes" in $$parsedSource) {
            $$parsedSource["scenes"] = $$createField4_0($$parsedSource["scenes"]);
        }
        if ("locators" in $$parsedSource) {
            $$parsedSource["locators"] = $$createField5_0($$parsedSource["locators"]);
        }
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField6_0($$parsedSource["tracks"]);
        }
        if ("main" in $$parsedSource) {
            $$parsedSource["main"] = $$createField7_0($$parsedSource["main"]);
        }
        return new Overview($$parsedSource as Partial<Overview>);
    }
}

export class TrackSummary {
    "id": string;
    "name": string;

    /**
     * midi | audio | group | return | main
     */
    "kind": string;

    /**
     * Live's color index (0-69), -1 for none
     */
    "color": number;

    /**
     * the group track's id, "" when in none
     */
    "group": string;
    "folded": boolean;

    /**
     * dB; -inf is -1000
     */
    "volume": number;

    /**
     * the track activator is off
     */
    "muted": boolean;
    "solo": boolean;
    "devices": string[];
    "clips": ClipSummary[];

    /** Creates a new TrackSummary instance. */
    constructor($$source: Partial<TrackSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = 0;
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("folded" in $$source)) {
            this["folded"] = false;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("muted" in $$source)) {
            this["muted"] = false;
        }
        if (!("solo" in $$source)) {
            this["solo"] = false;
        }
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }
        if (!("clips" in $$source)) {
            this["clips"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackSummary {
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField9_0($$parsedSource["devices"]);
        }
        if ("clips" in $$parsedSource) {
            $$parsedSource["clips"] = $$createField10_0($$parsedSource["clips"]);
        }
        return new TrackSummary($$parsedSource as Partial<TrackSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Locator.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = TrackSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ClipSummary.createFrom;
const $$createType6 = $Create.Array($$createType5);
